services:
  satellite-tracking:
    build:
      context: .
      dockerfile: SatelliteTracking.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
